name: my-sensein-book
options:
  bundleIdPrefix: com.sensein
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
targets:
  my-sensein-book:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
    info:
      path: Sources/App/Info.plist
      properties:
        CFBundleDisplayName: book
        CFBundleName: book
        NSHumanReadableCopyright: "© Kravitz Geroge"
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Сканирование QR-кода для привязки к серверу"
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sensein.book
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_DISPLAY_NAME: My.Sensein.Book
